apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: InfluxDB-k6
    uid: influxdb_k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    editable: true
